site_name: Wisp Forest Docs 
site_url: https://docs.wispforest.io
theme:
    name: null
    custom_dir: mkdocs-material/material
    palette:
        - scheme: slate
          primary: indigo
          accent: blue  
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

        - scheme: default
          primary: indigo
          accent: blue
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
    features:
        navigation.tabs
        navigation.indexes
        navigation.expand
        search.suggest
        search.share
        navigation.top
        content.code.annotate
    favicon: assets/favicon.png
    icon:
      logo: octicons/flame-16 
    language: en
    font:
        text: Fira Sans
        code: Fira Mono

copyright: "Documentation by <a style=\"color: #13A6F0;\" href=\"https://github.com/gliscowo\">glisco</a>, with assistance from the Wisp Forest team"
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xrwHKktV2d
    - icon: fontawesome/brands/github
      link: https://github.com/wisp-forest/
  projects:
      isometric-renders:
          repo: https://github.com/gliscowo/isometric-renders
          name: Isometric Renders
          icon: isometric-renders/icon.png
      owo:
          repo: https://github.com/wisp-forest/owo-lib
          name: oωo
          icon: owo/icon.png
      scatter:
          repo: https://github.com/gliscowo/scatter
          name: scatter
      docs:
          repo: https://github.com/wisp-forest/docs
          name: Wisp Forest
      numismatic-overhaul:
          repo: https://github.com/wisp-forest/numismatic-overhaul
          name: Numismatic Overhaul
      lavender:
          repo: https://github.com/wisp-forest/lavender
          name: Lavender
      gadget:
          repo: https://github.com/wisp-forest/gadget
          name: gadget
      alloy-forgery:
          repo: https://github.com/wisp-forest/alloy-forgery
          name: Alloy Forgery
      accessories:
          repo: https://github.com/wisp-forest/accessories
          name: Accessories
      limelight:
          repo: https://github.com/wisp-forest/limelight
          name: Limelight

extra_css:
    - overrides.css

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - footnotes
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - toc:
        permalink: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tilde
    - pymdownx.critic

nav:
    - Home:
        - index.md
        - faq.md
        - fabric-events.md
        - datapack-tutorial.md
    - Isometric Renders:
        - isometric-renders/home.md
        - isometric-renders/slash_isorender.md
        - isometric-renders/options.md
    - Numismatic Overhaul:
        - numismatic-overhaul/home.md
        - numismatic-overhaul/shop.md
        - numismatic-overhaul/trades.md
    - oωo:
        - owo/setup.md
        - owo/features.md
        - owo/registration.md
        - owo/item-groups.md
        - owo/recipe-remainders.md
        - owo/networking.md
        - owo/endec.md
        - owo/rich-translations.md
        - owo/system-properties.md
        - owo/renderdoc.md
        - Config:
            - owo/config/index.md
            - owo/config/getting-started.md
            - owo/config/constraints.md
            - owo/config/annotations.md
            - owo/config/synchronization.md
            - owo/config/options.md
        - UI:
          - owo/ui/index.md
          - owo/ui/getting-started.md
          - owo/ui/academy.md
          - owo/ui/component-basics.md
          - owo/ui/layout-basics.md
          - owo/ui/utility-components.md
          - owo/ui/components/index.md
          - owo/ui/components/button.md
          - owo/ui/components/checkbox.md
          - owo/ui/components/collapsible-container.md
          - owo/ui/components/dropdown.md
          - owo/ui/components/flow-layout.md
          - owo/ui/components/grid-layout.md
          - owo/ui/components/label.md
          - owo/ui/components/scroll-container.md
          - owo/ui/components/slider.md
          - owo/ui/components/templates.md
    - Lavender:
        - lavender/setup.md
        - lavender/getting-started.md
        - lavender/metadata-format.md
        - lavender/markdown-syntax.md
        - lavender/structures.md
        - lavender/writing-extensions.md
    - scatter:
        - scatter/home.md
        - scatter/upload.md
        - scatter/edit.md
        - scatter/config.md
    - gadget:
        - gadget/home.md
        - gadget/for_server_admins.md
        - gadget/entity_inspector.md
        - gadget/nbt_inspector.md
        - Packet Dumps:
            - gadget/packet-dumps/index.md
            - gadget/packet-dumps/quick_start.md
            - gadget/packet-dumps/custom_packets.md
    - Alloy Forgery:
        - alloy-forgery/home.md
        - alloy-forgery/adding-recipes-and-fuels.md
        - alloy-forgery/building-a-forge.md
        - alloy-forgery/recipe-adaptation.md
        - alloy-forgery/defining-a-forge.md
    - Accessories: 
        - accessories/home.md
        - accessories/faq.md
        - General:
            - accessories/general/slot_types.md
            - accessories/general/defaulted_slots.md
            - accessories/general/binding_accessories_to_slots.md
            - accessories/general/binding_slots_to_entities.md
            - accessories/general/slot_groups.md
            - accessories/general/adjusting_slot_amount.md
        - Developer:
            - accessories/developer/dev_setup.md
            - accessories/developer/api_fundamentals.md
            - accessories/developer/rendering_api.md
            - accessories/developer/api_events.md
            - accessories/developer/itemstack_components.md
    - Limelight:
        - limelight/index.md
        - Configuring:
            - limelight/configuring/adding_wikis.md
        - Extending:
            - limelight/extending/setup.md
            - limelight/extending/defining_extensions.md
            - limelight/extending/providing_results.md
            - limelight/extending/adding_wiki_sources.md